# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    strategy: 
      matrix: 
        elixir-version: [ '1.18.1', '1.17.3' ]
        otp-version: [ '27.2', '26.2.5.6', '25.3.2.16' ]

    steps:
    - name: Install OpenBLAS
      run: |
        sudo apt update
        sudo apt install libopenblas-dev
    - uses: actions/checkout@v4
    - name: Set up Elixir
      id: beam
      uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
