# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    strategy: 
      matrix: 
        elixir-version: [ '1.18.1', '1.17.3', '1.16.3' ]
        otp-version: [ '27.2', '26.2.5.6', '25.3.2.16' ]
        exclude:
          - elixir-version: '1.16.3'
            otp-version: '27.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      id: beam
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
